<div class="grid gap-4 md:grid-cols-3 xl:grid-cols-6">@foreach($operations as $label=>$value)<div class="luczor-card p-4"><div class="text-xs uppercase tracking-wider text-slate-500">{{ str_replace('_',' ',$label) }}</div><div class="mt-2 text-2xl font-semibold text-cyan-100">{{ $value }}</div></div>@endforeach</div>
<div class="mt-6 grid gap-4 lg:grid-cols-3">
    <x-ui.panel class="lg:col-span-2"><div class="flex items-baseline justify-between"><h2 class="font-semibold">Läufe / Tag <span class="text-xs text-slate-500">(14 T)</span></h2><span class="text-xs text-slate-400">{{ $charts['total_runs'] ?? 0 }} Läufe · ${{ $charts['total_cost'] ?? 0 }}</span></div>
        <svg viewBox="0 0 560 140" class="mt-3 w-full" preserveAspectRatio="none" role="img" aria-label="Läufe pro Tag">
            <line x1="0" y1="130" x2="560" y2="130" stroke="rgba(148,197,236,0.15)"/>
            @foreach(($charts['bars'] ?? []) as $b)<rect x="{{ $b['x'] }}" y="{{ $b['y'] }}" width="{{ $b['w'] }}" height="{{ $b['h'] }}" rx="2" fill="rgba(34,211,238,0.55)"><title>{{ $b['runs'] }} Läufe</title></rect><text x="{{ $b['x'] + $b['w']/2 }}" y="139" fill="rgba(107,142,166,0.8)" font-size="7" text-anchor="middle">{{ $b['day'] }}</text>@endforeach
            @if(!empty($charts['cost_points']))<polyline points="{{ $charts['cost_points'] }}" fill="none" stroke="rgb(245,158,11)" stroke-width="1.5" stroke-linejoin="round"/>@endif
        </svg>
        <div class="mt-1 flex gap-4 text-xs text-slate-500"><span><span class="inline-block h-2 w-2 rounded-sm" style="background:rgba(34,211,238,.55)"></span> Läufe</span><span><span class="inline-block h-2 w-2 rounded-sm" style="background:rgb(245,158,11)"></span> Kosten</span></div>
    </x-ui.panel>
    <x-ui.panel title="Provider (30 T)">
        <div class="mt-3 space-y-2">@forelse(($charts['providers'] ?? []) as $p)<div><div class="flex justify-between text-xs"><span class="text-slate-300">{{ $p['label'] }}</span><span class="text-slate-500">{{ $p['value'] }}</span></div><div class="mt-1 h-2 rounded bg-slate-800"><div class="h-2 rounded" style="width:{{ $p['pct'] }}%;background:rgba(34,211,238,.6)"></div></div></div>@empty<p class="text-xs text-slate-500">Noch keine Läufe.</p>@endforelse</div>
        <h2 class="mt-5 font-semibold">Workflow-Status</h2>
        <div class="mt-3 space-y-2">@forelse(($charts['workflow_status'] ?? []) as $s)<div><div class="flex justify-between text-xs"><span class="text-slate-300">{{ $s['label'] }}</span><span class="text-slate-500">{{ $s['value'] }}</span></div><div class="mt-1 h-2 rounded bg-slate-800"><div class="h-2 rounded" style="width:{{ $s['pct'] }}%;background:rgba(52,211,153,.6)"></div></div></div>@empty<p class="text-xs text-slate-500">Noch keine Läufe.</p>@endforelse</div>
    </x-ui.panel>
</div>
<div class="mt-8 grid gap-4 md:grid-cols-3"><a href="{{ route('admin.page','models') }}" class="luczor-card p-5 hover:border-cyan-400/40"><b>Modelle verwalten</b><p class="mt-2 text-sm text-slate-400">Free-Model-Ketten, Fallbacks und Messwerte.</p></a><a href="{{ route('admin.page','telemetry') }}" class="luczor-card p-5 hover:border-cyan-400/40"><b>Telemetry auswerten</b><p class="mt-2 text-sm text-slate-400">Kosten, Geschwindigkeit und Erfolgsrate.</p></a><a href="{{ route('admin.page','users') }}" class="luczor-card p-5 hover:border-cyan-400/40"><b>Benutzer verwalten</b><p class="mt-2 text-sm text-slate-400">User, Projekte, Geräte und Besitzzuordnung.</p></a><a href="{{ route('admin.page','costs') }}" class="luczor-card p-5 hover:border-cyan-400/40"><b>Kosten je Benutzer</b><p class="mt-2 text-sm text-slate-400">LLM-Kosten nach User, Projekt und Gerät.</p></a><a href="{{ route('admin.page','devices') }}" class="luczor-card p-5 hover:border-cyan-400/40"><b>Geraete debuggen</b><p class="mt-2 text-sm text-slate-400">Stille Debug-Anforderung und Download.</p></a><a href="{{ route('admin.page','workflows') }}" class="luczor-card p-5 hover:border-cyan-400/40"><b>Workflows</b><p class="mt-2 text-sm text-slate-400">AI-Abläufe orchestrieren, starten und exportieren.</p></a><a href="{{ route('admin.page','agents') }}" class="luczor-card p-5 hover:border-cyan-400/40"><b>Agenten & Ereignisse</b><p class="mt-2 text-sm text-slate-400">Agent-Läufe und Audit-Ereignisprotokoll.</p></a></div>
